name: Node.js CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: node modules
      run: npm install
    
    - name: building site
      run: npm run up
    
    - uses: actions/upload-artifact@v1
      with:
        name: st_webengineering
        path: dist
